---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name:
      - curl
      - wget
      - git
      - rsync
      - brotli
    state: present

- name: Create web directory
  file:
    path: "{{ app_root }}"
    state: directory
    mode: '0755'
