---
- name: Install Python dependencies
  apt:
    name:
      - python{{ python_version }}
      - python{{ python_version }}-venv
      - python{{ python_version }}-dev
      - python3-pip
    state: present
    update_cache: yes

- name: Install virtualenv
  pip:
    name: virtualenv
    state: present

- name: Create backend user
  user:
    name: "{{ backend_user }}"
    system: yes
    create_home: yes
    shell: /bin/false
    state: present

- name: Create backend log file
  file:
    path: "/var/log/{{ domain_name }}-backend.log"
    state: touch
    owner: "{{ backend_user }}"
    group: "{{ backend_user }}"
    mode: '0644' 