---
- name: Add NodeSource repository
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_{{ node_version }} | bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Node.js (includes npm)
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Update npm to latest version
  shell: npm install -g npm@latest
  changed_when: false 