---
- name: Install certbot and nginx plugin
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Create basic nginx config
  template:
    src: pre-ssl.conf.j2
    dest: /etc/nginx/sites-available/{{ domain_name }}

- name: Enable site configuration
  file:
    src: /etc/nginx/sites-available/{{ domain_name }}
    dest: /etc/nginx/sites-enabled/{{ domain_name }}
    state: link

- name: Restart nginx with basic config
  service:
    name: nginx
    state: restarted

- name: Obtain and install SSL certificate
  command: >
    certbot --nginx 
    -d {{ domain_name }}
    --non-interactive --agree-tos
    --email admin@{{ domain_name }}
